//! `StateFrame` — explicit, structured "current state" snapshot of an agent
//! session.
//!
//! Why (p6 of the harness architect plan):
//!
//! The rolling summary tells the agent *what has happened*. The state frame
//! tells the agent *where we are right now*: the currently active plan
//! items, the most recent successful tool calls, the last error (if any),
//! and the working directory. This is crucial when the user resumes a
//! historical session hours or days later — without a frame the agent has
//! to reconstruct its bearings from the compressed tail, which is exactly
//! the part that lost fidelity during compaction.
//!
//! The frame is:
//! - Persisted alongside the session (`sessions.state_frame_json`).
//! - Re-generated on every compaction pass and at the end of every user
//!   turn (so it's always fresh when the session is reopened).
//! - Injected into the context as a synthetic *user-role* text block,
//!   immediately after the rolling summary (if any) and before the real
//!   message history. We use the user role because many providers reject
//!   leading assistant messages and because this mirrors how rolling
//!   summary injection already works.

use serde::{Deserialize, Serialize};

/// The on-disk / on-wire representation of the frame. Kept JSON-friendly
/// so future fields can be added without bumping a version number.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct StateFrame {
    /// Plan/todo items currently known to be active. Rendered verbatim
    /// (one per line) so the agent can see what is still outstanding.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub active_plan_items: Vec<String>,
    /// Short textual sketches of the last few successful tool invocations,
    /// e.g. `"shell: ran cargo test; exit=0"`. Bounded to a handful of
    /// entries.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub recent_tool_calls: Vec<String>,
    /// Last tool error we saw (if any), useful for the agent to decide
    /// whether to retry or escalate to the user. `None` when the session
    /// is clean.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    /// Current working directory as known to the session. Optional: some
    /// sessions (pool, scheduler) don't have a single canonical cwd.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Free-form note generated by Level-2 summarisation (e.g. "Waiting
    /// for the user to approve the deployment diff"). Optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_step_hint: Option<String>,
    /// ISO-8601 timestamp of the last update. Stored as a string so we
    /// don't drag `chrono` into every `serde` use-site that just wants to
    /// round-trip the frame.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl StateFrame {
    pub fn is_empty(&self) -> bool {
        self.active_plan_items.is_empty()
            && self.recent_tool_calls.is_empty()
            && self.last_error.is_none()
            && self.cwd.is_none()
            && self.next_step_hint.is_none()
    }

    /// Serialize to JSON; returns `None` when the frame is empty so
    /// callers can cheaply skip the DB write.
    pub fn to_json(&self) -> Option<String> {
        if self.is_empty() {
            return None;
        }
        serde_json::to_string(self).ok()
    }

    /// Parse from DB storage. Returns `None` on malformed JSON rather
    /// than panicking — a corrupted frame should not block a session.
    pub fn from_json_opt(raw: &str) -> Option<Self> {
        if raw.trim().is_empty() {
            return None;
        }
        serde_json::from_str(raw).ok()
    }

    /// Render the frame as a human-readable text block that goes into
    /// the LLM context. Kept compact (≤500 chars in the common case) so
    /// it does not dominate the user turn.
    pub fn render_text(&self) -> String {
        let mut out = String::with_capacity(256);
        out.push_str("[会话状态帧 / session state frame]\n");
        if let Some(cwd) = &self.cwd {
            out.push_str(&format!("工作目录 cwd: {}\n", cwd));
        }
        if !self.active_plan_items.is_empty() {
            out.push_str("当前待办 / active plan:\n");
            for item in &self.active_plan_items {
                out.push_str(&format!("  - {}\n", item));
            }
        }
        if !self.recent_tool_calls.is_empty() {
            out.push_str("近期工具 / recent tool calls:\n");
            for call in &self.recent_tool_calls {
                out.push_str(&format!("  - {}\n", call));
            }
        }
        if let Some(err) = &self.last_error {
            out.push_str(&format!("上次错误 / last error: {}\n", err));
        }
        if let Some(hint) = &self.next_step_hint {
            out.push_str(&format!("下一步提示 / next step: {}\n", hint));
        }
        out.push_str(
            "\n[系统提示] 以上是会话恢复时的状态快照，请基于此继续任务，不要重复已完成的工作。",
        );
        out
    }
}

/// Build an `LlmMessage` that injects the frame as a synthetic user turn.
///
/// Co-located with `rolling_summary_message` in spirit: same role, same
/// "synthetic context note" shape, so the downstream sanitisation pipeline
/// treats it identically.
pub fn state_frame_message(frame: &StateFrame) -> crate::llm::LlmMessage {
    crate::llm::LlmMessage {
        role: "user".into(),
        content: crate::llm::MessageContent::text(frame.render_text()),
    }
}

/// Derive a best-effort state frame from the tail of an in-flight agent
/// conversation. Used by the agent loop right after a rolling summary is
/// persisted so the frame stays aligned with the summary cadence.
///
/// Heuristics:
/// - Scan the last `scan_window` messages (default 24) newest-first.
/// - Record the 5 most recent successful `ToolUse` calls as short
///   `"<tool_name>: <arg hint>"` strings.
/// - Record the most recent `is_error=true` `ToolResult` as `last_error`.
/// - Leave `cwd` / `active_plan_items` / `next_step_hint` for higher
///   layers (plan tracker, scene factory) to fill in; they always know
///   more than a post-hoc scan does.
pub fn derive_frame_from_tail(
    messages: &[crate::llm::LlmMessage],
    scan_window: usize,
) -> StateFrame {
    use crate::llm::{ContentBlock, MessageContent};

    let mut frame = StateFrame::default();
    let window = scan_window.max(1);
    let start = messages.len().saturating_sub(window);
    let slice = &messages[start..];

    let mut last_error: Option<String> = None;
    let mut recent_calls: Vec<String> = Vec::new();

    for m in slice.iter().rev() {
        if recent_calls.len() >= 5 && last_error.is_some() {
            break;
        }
        if let MessageContent::Blocks(blocks) = &m.content {
            for b in blocks.iter().rev() {
                match b {
                    ContentBlock::ToolUse { name, input, .. } if recent_calls.len() < 5 => {
                        let hint = short_input_hint(input);
                        recent_calls.push(if hint.is_empty() {
                            name.clone()
                        } else {
                            format!("{}: {}", name, hint)
                        });
                    }
                    ContentBlock::ToolResult {
                        is_error, content, ..
                    } if *is_error && last_error.is_none() => {
                        let first_line: String = content
                            .lines()
                            .next()
                            .unwrap_or("")
                            .chars()
                            .take(160)
                            .collect();
                        if !first_line.is_empty() {
                            last_error = Some(first_line);
                        }
                    }
                    _ => {}
                }
            }
        }
    }
    recent_calls.reverse();
    frame.recent_tool_calls = recent_calls;
    frame.last_error = last_error;
    frame.updated_at = Some(chrono::Utc::now().to_rfc3339());
    frame
}

/// Shorten a tool input Value to a single-line hint (≤ 60 chars) for the
/// frame's `recent_tool_calls` entries. Deliberately deterministic so the
/// frame is diffable across calls.
fn short_input_hint(input: &serde_json::Value) -> String {
    let raw = if let Some(s) = input.get("command").and_then(|v| v.as_str()) {
        s.to_string()
    } else if let Some(s) = input.get("path").and_then(|v| v.as_str()) {
        s.to_string()
    } else if let Some(s) = input.get("query").and_then(|v| v.as_str()) {
        s.to_string()
    } else if let Some(s) = input.get("url").and_then(|v| v.as_str()) {
        s.to_string()
    } else if let Some(s) = input.get("action").and_then(|v| v.as_str()) {
        s.to_string()
    } else {
        return String::new();
    };
    let trimmed = raw.trim();
    if trimmed.chars().count() <= 60 {
        trimmed.to_string()
    } else {
        trimmed.chars().take(57).collect::<String>() + "…"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_frame_round_trips_as_none() {
        let frame = StateFrame::default();
        assert!(frame.is_empty());
        assert!(frame.to_json().is_none());
    }

    #[test]
    fn json_round_trip_preserves_fields() {
        let frame = StateFrame {
            active_plan_items: vec!["写 p6 测试".into(), "跑 eval".into()],
            recent_tool_calls: vec!["shell: cargo test (exit=0)".into()],
            last_error: None,
            cwd: Some("C:/Users/zzz/Projects/piscidesktop".into()),
            next_step_hint: Some("等待用户确认".into()),
            updated_at: Some("2026-04-18T10:00:00Z".into()),
        };
        let json = frame.to_json().expect("serialize");
        let parsed = StateFrame::from_json_opt(&json).expect("parse");
        assert_eq!(parsed, frame);
    }

    #[test]
    fn malformed_json_returns_none_not_panic() {
        assert!(StateFrame::from_json_opt("{not json").is_none());
        assert!(StateFrame::from_json_opt("").is_none());
        assert!(StateFrame::from_json_opt("   ").is_none());
    }

    #[test]
    fn rendered_text_contains_all_sections() {
        let frame = StateFrame {
            active_plan_items: vec!["一号任务".into()],
            recent_tool_calls: vec!["shell: ls".into()],
            last_error: Some("permission denied".into()),
            cwd: Some("/tmp".into()),
            next_step_hint: Some("继续".into()),
            updated_at: None,
        };
        let text = frame.render_text();
        assert!(text.contains("一号任务"));
        assert!(text.contains("shell: ls"));
        assert!(text.contains("permission denied"));
        assert!(text.contains("/tmp"));
        assert!(text.contains("继续"));
        assert!(text.contains("[系统提示]"));
    }

    #[test]
    fn derives_recent_tool_calls_and_last_error_from_tail() {
        use crate::llm::{ContentBlock, LlmMessage, MessageContent};
        use serde_json::json;
        let msgs = vec![
            LlmMessage {
                role: "user".into(),
                content: MessageContent::text("task"),
            },
            LlmMessage {
                role: "assistant".into(),
                content: MessageContent::Blocks(vec![ContentBlock::ToolUse {
                    id: "a".into(),
                    name: "shell".into(),
                    input: json!({"command": "ls -la"}),
                }]),
            },
            LlmMessage {
                role: "user".into(),
                content: MessageContent::Blocks(vec![ContentBlock::ToolResult {
                    tool_use_id: "a".into(),
                    content: "permission denied\nmore".into(),
                    is_error: true,
                }]),
            },
            LlmMessage {
                role: "assistant".into(),
                content: MessageContent::Blocks(vec![ContentBlock::ToolUse {
                    id: "b".into(),
                    name: "file_read".into(),
                    input: json!({"path": "C:/x.rs"}),
                }]),
            },
        ];
        let frame = derive_frame_from_tail(&msgs, 24);
        assert_eq!(frame.recent_tool_calls.len(), 2);
        assert!(frame.recent_tool_calls.iter().any(|c| c.contains("shell")));
        assert!(frame
            .recent_tool_calls
            .iter()
            .any(|c| c.contains("file_read")));
        assert_eq!(frame.last_error.as_deref(), Some("permission denied"));
        assert!(frame.updated_at.is_some());
    }

    #[test]
    fn derives_empty_frame_from_pure_text_history() {
        use crate::llm::{LlmMessage, MessageContent};
        let msgs = vec![
            LlmMessage {
                role: "user".into(),
                content: MessageContent::text("hi"),
            },
            LlmMessage {
                role: "assistant".into(),
                content: MessageContent::text("hello"),
            },
        ];
        let frame = derive_frame_from_tail(&msgs, 24);
        assert!(frame.recent_tool_calls.is_empty());
        assert!(frame.last_error.is_none());
        // updated_at is still set (the frame is non-empty only if there are calls/errors).
        assert!(frame.is_empty());
    }

    #[test]
    fn state_frame_message_uses_user_role() {
        let frame = StateFrame {
            cwd: Some("/x".into()),
            ..Default::default()
        };
        let msg = state_frame_message(&frame);
        assert_eq!(msg.role, "user");
        let text = msg.content.as_text();
        assert!(text.contains("[会话状态帧"));
    }
}
